import Script from 'next/script';
import { Inter } from 'next/font/google';
import './globals.css';
import 'tailwindcss/tailwind.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Use Script component for asynchronous script loading */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive" // or "afterInteractive", depending on when you need the script
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
